scene_from_tracking:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
near_z: 0.01
far_z: 100.0
resolution_scale: 1.0
default_image_type: street
eye_image_types:
  left: street
  right: street
default_image_rect:
  width: 1832
  height: 1920
